### ISSUE TITLE
Unsupported operand type in Datetimeutils.now()

### ISSUE THREAD

**Issue by user2684** [egeoffrey/egeoffrey-sdk#1]
**Describe the bug**
For undetermined reasons the error message below is continuously generated consuming 100% of the CPU 

**Version**
1.0-33

**To Reproduce**
Unknown

**Screenshots**
```
[2019-10-22 08:27:49][controller/db] ERROR: runtime error during on_message(): Traceback (most recent call last):|  File "sdk/python/module/helpers/mqtt_consumer.py", line 99, in on_message_consume|    self.mqtt_client.module.on_message(message)|  File "controller/db.py", line 373, in on_message|    self.set(key, message.get_data(), self.date.now(), False)|  File "sdk/python/utils/datetimeutils.py", line 23, in now|    return self.timezone(int(time.time()))|  File "sdk/python/utils/datetimeutils.py", line 15, in timezone|    return int(timestamp+self.__utc_offset*3600)|TypeError: unsupported operand type(s) for +: 'int' and 'unicode'|
```

**Comment by user2684** [comment]
Added safeguard when creating the object and passing the utc offset
