### ISSUE TITLE
Unable to remove scheduled job for sensor

### ISSUE THREAD

**Issue by user2684** [egeoffrey/egeoffrey-sdk#6]
**Describe the bug**
Under unknown circumstances, the following error is thrown for multiple sensors upon a restart:

`
Unable to remove scheduled job for sensor system/load/load_1: Traceback (most recent call last):|  File "sdk/python/module/service.py", line 47, in __remove_schedule|    self.__scheduler.remove_job(self.__jobs[sensor_id])|  File "sdk/python/module/helpers/scheduler.py", line 121, in remove_job|    return self.__scheduler.remove_job(id)|  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 621, in remove_job|    raise JobLookupError(job_id)|JobLookupError: u'No job by the id of 08ffe43cf2b047ebaab48814f1a8aff9 was found'|
`

Could be because __remove_schedule() does not delete the job from __jobs after removing it.

**Version**
v1.0-35

**Comment by user2684** [comment]
Added additional safeguard by listing running jobs
